export enum QueryOrderEnum {
    NAME = "name",
    SURNAME = "surname",
    EMAIL = "email",
    PHONE = "phone",
    AGE = "age",
    COURSE = "course",
    COURSE_FORMAT = "course_format",
    COURSE_TYPE = "course_type",
    STATUS = "status",
    SUM = "sum",
    ALREADY_PAID = "already_paid",
    GROUP = "group",
    CREATED_AT = "created_at",
    MANAGER = "manager",
}